config/routes.rb
Rails.application.routes.draw do
  root 'holes#index'

  delete "/logout" => "sessions#destroy", as: :logout
  get "/auth/:provider/callback" => "sessions#create"

  resources :holes
  post '/search_result' => 'holes#search_result'

end

app/models/hole.rb
class Hole < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :uid, :provider, presence: true

  def self.find_or_create_from_omniauth(auth_hash)
    user = self.find_by(uid: auth_hash["uid"], provider: auth_hash["provider"])
    if !user.nil?
      return user
    else
      user = User.new
      user.provider = auth_hash["provider"]
      user.uid = auth_hash["uid"]
      user.name = auth_hash["info"]["name"]
      user.email = auth_hash["info"]["email"]
      user.photo = auth_hash["info"]["image"]
    end
    if user.save
      return user
    else
      return nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @user ||= User.find_by(id: session[:user_id])
  end

  def require_login
    if current_user.nil?
      flash[:error] = "You must be logged in to view this section"
      redirect_to root_path
    end
  end
end

app/controllers/holes_controller.rb
require "#{Rails.root}/lib/Geocode.rb"
class HolesController < ApplicationController
  before_action :require_login, only: [:create, :show, :destroy]

  def index

  end
  def new
    @hole = Hole.new
  end

  def create
    @hole = Hole.new
    @hole.current_user_id = params[:current_user_id]
    @hole.origen_address = params[:origen_address]
    @hole.origin_latitud = params[:origin_latitud]
    @hole.origin_longitud = params[:origin_longitud]
    @hole.origin_image = params[:origin_image]
    @hole.destination_address = params[:destination_address]
    @hole.destination_latitud = params[:destination_latitud]
    @hole.destination_longitud = params[:destination_longitud]
    @hole.destination_image = params[:destination_image]

    @hole.save
    if @hole.save
      redirect_to hole_path(@hole.current_user_id)
    else
      render :index
    end
  end

  def show
    @holes = Hole.where(current_user_id: params[:id])
  end

  def destroy
    Hole.delete(params[:id])
    redirect_to hole_path(current_user.uid)
  end


  def search_result
    data = Geocode.find(params[:user_input])
    if data.nil?
      flash.now[:notice] = "Something went wrong, please try again"
    else
      @location = data
      @user_input = params[:user_input]
      @destination_latitud = @location.latitud
      @destination_longitud = @location.longitud * (-1)
      @destination = Geocode.find_destination(@destination_latitud,@destination_longitud)
      if @destination.formatted_address
         if @destination.formatted_address.include? "China"
           place = @destination.formatted_address.split(',')
           if place[0][/\d+/].nil?
             @destination = Geocode.find("#{place[0]}, #{place[1]}")
           else
             @destination = Geocode.find(place[1])
         end
        end
      end
      render :index
    end

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth_hash = request.env['omniauth.auth']
    user = User.find_or_create_from_omniauth(auth_hash)

    if user
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:notice] = "did not login in"
      redirect_to root_path
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/holes_helper.rb
module HolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/holes/index.html.erb
<h1>Welcome to Digging Holes</h1>
<p>Please enter the origin of your hole<%=", " + current_user.name if current_user%></p>
<br><br>
<%= form_tag search_result_path, class: "input-group input-group-lg" do  %>
<%= text_field_tag :user_input, nil, class: 'form-control', placeholder: 'Start my hole at' %>
<span class="input-group-btn">
  <%= submit_tag "Search", class: 'btn btn-default'%>
</span>
<% end %>
<br><br>
<% if @location %>
<div class="panel panel-primary">
  <!-- Default panel contents -->

  <table class="table">
    <tr>
      <th>
        Origin
      </th>
      <th>
        Destination
      </th>
    </tr>
    <tr>
      <td>
        <p><strong>Address: </strong> <%=@location.formatted_address %></p>
        <p><strong>Latitud: </strong><%=@location.latitud %></p>
        <p><strong>Longitud: </strong><%=@location.longitud %></p>

        <%= image_tag("https://maps.googleapis.com/maps/api/streetview?size=420x420&location=#{@location.latitud},#{@location.longitud}")%>
      </td>
      <%if @destination != nil%>
      <td>
        <p><strong>Address: </strong> <%=@destination.formatted_address %></p>
        <p><strong>Latitud: </strong><%=@destination.latitud %></p>
        <p><strong>Longitud: </strong><%=@destination.longitud %></p>
        <div class="img-index">

        <%if @destination.place_id == nil %>
        <%= image_tag("https://maps.googleapis.com/maps/api/staticmap?center=#{@destination.latitud},#{@destination.longitud}&zoom=5&size=420x420") %>
        <%elsif @destination.formatted_address.include? "China"%>
        <%= image_tag("https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photoreference=#{@destination.photo_reference}&key=" + ENV["GOOGLE_KEY"])%>
        <%else%>
        <%= image_tag("https://maps.googleapis.com/maps/api/place/photo?maxwidth=420&photoreference=#{@destination.photo_reference}&key=" + ENV["GOOGLE_KEY"])%>
        <%= image_tag("https://maps.googleapis.com/maps/api/streetview?size=420x420&location=#{@destination.latitud},#{@destination.longitud}")%>
        <%end%>
      </div>
      </td>
    </tr>
    <%end%>

    <%if current_user != nil%>
    <tr>
      <td>
      </td>
      <td class="fava">
        <%= form_tag holes_path, method: :post do %>
        <%=hidden_field_tag :current_user_id, current_user.uid%>
        <%=hidden_field_tag :origen_address, @location.formatted_address %>
        <%=hidden_field_tag :origin_latitud, @location.latitud%>
        <%=hidden_field_tag :origin_longitud, @location.longitud%>
        <%=hidden_field_tag :origin_image, "https://maps.googleapis.com/maps/api/streetview?size=420x200&location=#{@location.latitud},#{@location.longitud}"%>
        <%=hidden_field_tag :destination_address, @destination.formatted_address %>
        <%=hidden_field_tag :destination_latitud, @destination.latitud%>
        <%=hidden_field_tag :destination_longitud, @destination.longitud%>
        <%=hidden_field_tag :destination_image, "https://maps.googleapis.com/maps/api/place/photo?maxwidth=420&photoreference=#{@destination.photo_reference}&key=" + ENV["GOOGLE_KEY"]%>

        <%=submit_tag 'Save Hole!!', class: "btn btn-primary"%>
        <%end%>
      </td>
    </tr>
    <%end%>
  </table>
</div>
<% end %>

app/views/holes/show.html.erb
<table class="table">
<%@holes.map do |hole|%>
  <tr>
    <td>
      <p><strong>Address: </strong><%=hole.origen_address%></p>
      <p><strong>Latitud: </strong><%=hole.origin_latitud%></p>
      <p><strong>Longitud: </strong><%=hole.origin_longitud%></p>
      <%=image_tag hole.origin_image%>
    </td>
    <td>
      <p><strong>Address: </strong><%=hole.destination_address%></p>
      <p><strong>Latitud: </strong><%=hole.destination_latitud%></p>
      <p><strong>Longitud: </strong><%=hole.destination_longitud%></p>

      <div class="img-show">
      <% if hole.destination_address.empty? %>
      <%= image_tag("https://maps.googleapis.com/maps/api/staticmap?center=#{hole.destination_latitud},#{hole.destination_longitud}&zoom=5&size=420x200") %>
      <%else%>
      <%=image_tag hole.destination_image%>
      </div>
      <% end %>
    </td>

  </tr>
  <tr>
    <td></td>
    <td>
      <%=button_to "Delete this hole", hole, method: :delete, class: "btn btn-primary", data: { confirm: "Are you sure?" } %>
    </td>
  </tr>

<%end%>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Digging</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

 </head>
 <body>

   <nav class="navbar navbar-inverse">
     <div class="container-fluid">
         <!-- Brand and toggle get grouped for better mobile display -->
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <%=link_to "Digging Holes", root_path, class: 'navbar-brand'%>
       </div>

       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         <ul class="nav navbar-nav">
           <li><%= form_tag search_result_path, class: "navbar-form navbar-left" do  %>
             <div class="form-group">
               <%= text_field_tag :user_input, nil, class: 'form-control' %>
             </div>
             <%= submit_tag "Search", class: 'btn btn-default'%>
             <% end %>
           </li>
           <li><%=link_to "My Holes", hole_path(current_user.uid) if current_user%></li>
         </ul>
         <ul class="nav navbar-nav navbar-right">

           <%if current_user%>
           <span class="name"><%=current_user.name %></span>
           <li><%=link_to "Log Out", logout_path, method: :delete, class: "totheleft" %> </li>
           <%=image_tag current_user.photo, class: "picprofile" %>
           <% end %>
           <li><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" unless current_user%> </li>

             </div>
           </ul>
       </div><!-- /.container-fluid -->
     </nav>

<br><br>

<% if flash[:notice] -%>
<div class="alert alert-warning" role="alert">
  <p class='notice'><%=h flash[:notice] %></p>
</div>
<% end %>
<div class="container">


<%= yield %>

</div>
</body>
</html>